version: "3.9"
services:
  web:
    # container_name: "nginx"
    build:
      dockerfile: "./container/web/Dockerfile"
    ports:
      - "80:80"
    volumes:
      - "./src/php:/var/www/html"
      - "vendor:/var/www/html/vendor"
      - "./work:/work"
  php:
    # container_name: "laravel"
    build:
      dockerfile: "./container/php/Dockerfile"
    ports:
      - "9000:9000"
      - "5173:5173"
    volumes:
      - "./src/php:/var/www/html"
      - "vendor:/var/www/html/vendor"
      - "./work:/work"
  db2:
    # container_name: "mysql"
    image: mysql:8.0
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "TZ='Asia/Tokyo'"
    volumes:
      - "./db2:/var/lib/mysql"
      - "./work:/work"
    # MySQL8.0ではデフォルトが"caching_sha2_password"で、ドライバが非対応のため変更
    command: --default-authentication-plugin=mysql_native_password && mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
volumes:            # 追加
  vendor:     # 追加